<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= htmlspecialchars($vendor['shop_name']) ?> | Lokal Culture</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/vendor.css"><link rel="stylesheet" href="/assets/css/admin.css"></head>
<body class="dashboard-page">
<header class="site-header"><a class="brand" href="/">✦ LOKAL <em>CULTURE</em></a><nav class="header-actions"><a href="/admin/vendors">All vendors</a><a href="/account">Dashboard</a></nav></header>
<main class="vendor-management">
    <p class="eyebrow">Vendor review</p><h1><?= htmlspecialchars($vendor['shop_name']) ?></h1><p><?= htmlspecialchars($vendor['description'] ?? '') ?></p>
    <div class="management-table"><div class="management-row"><span>Contact</span><strong><?= htmlspecialchars($vendor['contact_name']) ?> · <?= htmlspecialchars($vendor['email']) ?></strong></div><div class="management-row"><span>Registered address</span><strong><?= htmlspecialchars($vendor['registered_address'] ?? 'Not provided') ?>, <?= htmlspecialchars($vendor['state'] ?? 'State missing') ?> <?= htmlspecialchars($vendor['postal_code'] ?? '') ?></strong></div><div class="management-row"><span>Regional focus</span><strong><?= htmlspecialchars($vendor['region'] ?? 'Not provided') ?> · <?= htmlspecialchars($vendor['craft_specialty'] ?? 'Not provided') ?></strong></div><div class="management-row"><span>GST information</span><strong><?= htmlspecialchars($vendor['gstin'] ?? 'Not provided') ?> · <?= htmlspecialchars($vendor['gst_status']) ?></strong></div><div class="management-row"><span>Products</span><strong><?= htmlspecialchars((string) $vendor['product_count']) ?></strong></div></div>
    <section class="approval-actions">
        <form method="post" action="/admin/vendors"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="vendor_id" value="<?= htmlspecialchars((string) $vendor['id']) ?>"><input type="hidden" name="action" value="verify"><button class="button" name="status" value="approved" type="submit">Approve vendor</button><button class="button button-muted" name="status" value="rejected" type="submit">Reject vendor</button></form>
        <?php if ($vendor['verification_status'] === 'approved'): ?><form method="post" action="/admin/vendors"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="vendor_id" value="<?= htmlspecialchars((string) $vendor['id']) ?>"><input type="hidden" name="action" value="active"><input type="hidden" name="is_active" value="<?= $vendor['is_active'] ? '0' : '1' ?>"><button class="button" type="submit"><?= $vendor['is_active'] ? 'Deactivate shop' : 'Activate shop' ?></button></form><?php endif; ?>
        <form class="vendor-form" method="post" action="/admin/vendors"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="vendor_id" value="<?= htmlspecialchars((string) $vendor['id']) ?>"><input type="hidden" name="action" value="commission"><label>Vendor commission (%)<input name="commission_rate" type="number" min="0" max="100" step="0.01" value="<?= htmlspecialchars((string) $vendor['commission_rate']) ?>"></label><button class="button" type="submit">Save commission</button></form>
    </section>
</main>
</body>
</html>
