<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Categories | Lokal Culture</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/vendor.css"><link rel="stylesheet" href="/assets/css/admin.css"></head>
<body class="dashboard-page">
<header class="site-header"><a class="brand" href="/">✦ LOKAL <em>CULTURE</em></a><nav class="header-actions"><a href="/account">Dashboard</a><a href="/admin/vendors">Vendors</a></nav></header>
<main class="vendor-management"><p class="eyebrow">Administrator workspace</p><h1>Categories</h1><p>Keep the marketplace taxonomy clear for regional and craft discovery.</p><?php if ($error): ?><p class="auth-error"><?= htmlspecialchars($error) ?></p><?php endif; ?>
<form class="vendor-form" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="action" value="create"><label>Name<input name="name" required maxlength="120"></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" maxlength="150"></label><label>Parent<select name="parent_id"><option value="">Top-level category</option><?php foreach ($categories as $category): ?><?php if ($category['is_active']): ?><option value="<?= htmlspecialchars((string) $category['id']) ?>"><?= htmlspecialchars($category['name']) ?></option><?php endif; ?><?php endforeach; ?></select></label><button class="button" type="submit">Create category <span>+</span></button></form>
<div class="management-table"><div class="management-row management-header"><span>Category</span><span>Slug</span><span>Status</span><span>Actions</span></div><?php foreach ($categories as $category): ?><div class="management-row"><form method="post" class="managed-product"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="action" value="update"><input type="hidden" name="category_id" value="<?= htmlspecialchars((string) $category['id']) ?>"><input name="name" value="<?= htmlspecialchars($category['name']) ?>" required><input name="slug" value="<?= htmlspecialchars($category['slug']) ?>" required></form><span><?= htmlspecialchars($category['slug']) ?></span><span><?= $category['is_active'] ? 'Active' : 'Archived' ?></span><span><button class="button" formmethod="post" type="submit">Save</button><?php if ($category['is_active']): ?><form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="action" value="archive"><input type="hidden" name="category_id" value="<?= htmlspecialchars((string) $category['id']) ?>"><button class="button button-muted" type="submit">Archive</button></form><?php endif; ?></span></div><?php endforeach; ?></div>
</main>
</body>
</html>
