<?php

declare(strict_types=1);

return [
    '/' => 'home',
    '/shop' => 'shop',
    '/search/suggest' => 'search-suggest',
    '/stories' => 'stories',
    '/cart' => 'cart',
    '/cart/add' => 'cart-add',
    '/cart/update' => 'cart-update',
    '/checkout' => 'checkout',
    '/orders' => 'orders',
    '/profile' => 'profile',
    '/addresses' => 'addresses',
    '/wishlist' => 'wishlist',
    '/wishlist/toggle' => 'wishlist-toggle',
    '/orders/cancel' => 'order-cancel',
    '/orders/return' => 'order-return',
    '/vendor/orders' => 'vendor-orders',
    '/admin/orders' => 'admin-orders',
    '/admin/orders/status' => 'admin-order-status',
    '/admin/orders/expire-pending' => 'admin-orders-expire-pending',
    '/admin/orders/returns/review' => 'admin-return-review',
    '/vendor/orders/status' => 'vendor-order-status',
    '/vendor/payouts' => 'vendor-payouts',
    '/vendor/payouts/request' => 'vendor-payout-request',
    '/vendor/bank' => 'vendor-bank',
    '/vendor/report' => 'vendor-report',
    '/admin/payouts' => 'admin-payouts',
    '/admin/payouts/review' => 'admin-payout-review',
    '/invoice' => 'invoice',
    '/payment' => 'payment',
    '/payment/verify' => 'payment-verify',
    '/payment/webhook' => 'payment-webhook',
    '/vendors' => 'vendors',
    '/product' => 'product',
    '/vendor' => 'vendor',
    '/vendor/products' => 'vendor-products',
    '/vendor/products/new' => 'vendor-product-new',
    '/admin/products' => 'admin-products',
    '/admin/stories' => 'admin-stories',
    '/admin/vendors' => 'admin-vendors',
    '/admin/categories' => 'admin-categories',
    '/vendor/register' => 'vendor-register',
    '/login' => 'login',
    '/register' => 'register',
    '/account' => 'account',
    '/logout' => 'logout',
    '/dashboard' => 'dashboard',
    '/robots.txt' => 'robots',
    '/sitemap.xml' => 'sitemap',
];